version: 2
jobs:
  build: .
  test:
    docker:
      - image: circleci/node
      - image: mongo

    working_directory: ~/snacks-machine
    steps:
      - checkout
      - run:
        name: Test
        command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build