version: 2
dependencies:
  override:
    - nvm install 8 && npm install
jobs:
  build: .
  test:
    docker:
      - image: circleci/node:8
      - image: mongo
    dependencies:
      override:
        - nvm use 8 && npm test
      environment:
        URL_MONGO_TEST=mongodb://localhost:27017/snacks_test
      working_directory: ~/snacks-machine
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: instal-babel
          command: 'sudo npm install --global babel-cli'
            - run:
          name: babel-core
          command: 'npm install --save-dev babel-core'
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
          environment:
            URL_MONGO_TEST=mongodb://localhost:27017/snacks_test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build