version: 2
jobs:
  build: .
  test:
    docker:
      - image: circleci/node
      - image: mongo

    working_directory: ~/snacks-machine
    steps:
      - checkout
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
          environment:
            URL_MONGO_TEST=mongodb://db:27017/snacks_test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build