version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8
      - image: mongo

    working_directory: ~/snacks-machine
    
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: instal-babel
          command: 'sudo npm install --global babel-cli'
            - run:
          name: babel-core
          command: 'npm install --save-dev babel-core'
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Test
          command: npm test
          environment:
            URL_MONGO_TEST=mongodb://localhost:27017/snacks_test